apiVersion: v1
kind: ConfigMap
metadata:
  name: scan-script
  namespace: kube-system
data:
  entrypoint.sh: |-
    #!/bin/bash
    for i in $NODES; do
      for p in $(seq $START_PORT $END_PORT); do
        hostname -i >/dev/tcp/$i/$p
      done
    done
    sleep infinity
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scan
  namespace: kube-system
  labels:
    name: scan
spec:
  selector:
    matchLabels:
      name: scan
  minReadySeconds: 0
  template:
    metadata:
      labels:
        name: scan
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      hostPID: false
      terminationGracePeriodSeconds: 0
      volumes:
      - name: scan-script
        configMap:
          defaultMode: 0700
          name: scan-script
      containers:
        - name: scan
          image: ubuntu:18.04
          command:
          - /entrypoint.sh
          volumeMounts:
          - name: scan-script
            mountPath: /entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          env:
            - name: START_PORT
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: start_port
            - name: END_PORT
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: end_port
            - name: NODES
              valueFrom:
                configMapKeyRef:
                  name: preflight-config
                  key: nodes
